server:
  port: 8092
  servlet:
    context-path: /diary

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db"
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: ALWAYS


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"


